import React from 'react';
import { motion } from 'motion/react';
import { Sparkles, Brain, Heart, Activity, Droplet, Sun, Moon, Zap, Coffee, ChevronRight } from 'lucide-react';

interface DetailedHealthReportProps {
  report: any;
  onClose: () => void;
}

export const DetailedHealthReport = ({ report, onClose }: DetailedHealthReportProps) => {
  return (
    <motion.div 
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      className="absolute inset-0 z-50 bg-[#0f1115] rounded-3xl overflow-y-auto overflow-x-hidden border border-gray-800 shadow-2xl p-8 flex flex-col"
    >
      <div className="flex items-center justify-between mb-8">
        <div>
          <h2 className="text-3xl font-serif font-bold text-transparent bg-clip-text bg-gradient-to-r from-amber-200 to-amber-500 flex items-center gap-3">
            <Sparkles className="w-8 h-8 text-amber-400" />
            Magical Biometric Analysis
          </h2>
          <p className="text-gray-400 mt-2">Comprehensive health and dermatological insights generated by AI.</p>
        </div>
        <button 
          onClick={onClose}
          className="px-6 py-3 rounded-full bg-emerald-900/30 hover:bg-emerald-800/40 border border-emerald-500/30 text-emerald-300 font-semibold transition-all"
        >
          Return to Hub
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        
        {/* Category: Wellness & Cognitive */}
        <ReportSection title="Wellness & Cognitive" icon={<Brain className="w-5 h-5 text-violet-400" />} color="violet">
          <ReportItem label="Energy Score" value={report.energyScore} unit="/ 100" />
          <ReportItem label="Recovery Score" value={report.recoveryScore} unit="/ 100" />
          <ReportItem label="Stress Level" value={report.stressLevel || 'Normal'} />
          <ReportItem label="Fatigue Score" value={report.fatigueScore || 'Minimal'} />
          <ReportItem label="Sleep Quality" value={report.sleepQualityEstimation} />
          <ReportItem label="Mood Detection" value={report.moodDetection} />
        </ReportSection>

        {/* Category: Dermatological */}
        <ReportSection title="Dermatological" icon={<Droplet className="w-5 h-5 text-cyan-400" />} color="cyan">
          <ReportItem label="Skin Age" value={report.skinAge} unit="Years" />
          <ReportItem label="Hydration" value={report.hydration} />
          <ReportItem label="Wrinkles" value={report.wrinkles} />
          <ReportItem label="Skin Tone" value={report.skinTone} />
          <ReportItem label="Pigmentation" value={report.pigmentation} />
          <ReportItem label="Dark Circles" value={report.darkCircles} />
        </ReportSection>

        {/* Category: Morphological & Facial */}
        <ReportSection title="Morphology & Adiposity" icon={<Activity className="w-5 h-5 text-rose-400" />} color="rose">
          <ReportItem label="Face Shape" value={report.faceShape} />
          <ReportItem label="Facial Symmetry" value={report.facialSymmetry} />
          <ReportItem label="Jawline Definition" value={report.jawlineDefinition} />
          <ReportItem label="Face Fat %" value={report.faceFatPercentage} unit="%" />
          <ReportItem label="Est. Body Fat" value={report.bodyFatEstimation} unit="%" />
          <ReportItem label="Double Chin" value={report.doubleChinDetection} />
          <ReportItem label="Neck Fat" value={report.neckFat} />
        </ReportSection>

      </div>
    </motion.div>
  );
};

const ReportSection = ({ title, icon, color, children }: any) => {
  const colorClasses: Record<string, string> = {
    violet: 'border-violet-500/20 bg-violet-500/5',
    cyan: 'border-cyan-500/20 bg-cyan-500/5',
    rose: 'border-rose-500/20 bg-rose-500/5',
  };

  return (
    <div className={`p-6 rounded-2xl border ${colorClasses[color]} flex flex-col gap-4`}>
      <h3 className="text-lg font-bold text-gray-200 flex items-center gap-2 mb-2">
        {icon} {title}
      </h3>
      <div className="flex flex-col gap-3">
        {children}
      </div>
    </div>
  );
};

const ReportItem = ({ label, value, unit }: any) => (
  <div className="flex items-center justify-between border-b border-gray-800/50 pb-2">
    <span className="text-gray-400 text-sm">{label}</span>
    <span className="text-gray-100 font-medium text-sm text-right">
      {value !== undefined ? value : '--'} {unit && <span className="text-gray-500 text-xs ml-1">{unit}</span>}
    </span>
  </div>
);
